[package]
name = "goon-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
rand = "0.8"
image = "0.25"
walkdir = "2"
ollama-rs = "0.2"
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }
url = "2.5"
